on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Scala Steward

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # this is needed for workflows to be dispatched for PRs created via steward
          # https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow?utm_source=chatgpt.com#triggering-a-workflow-from-a-workflow
          github-token: ${{ secrets.STEWARD_PAT }}
